modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CAPTERSERS/Advanced-Vanilla/issues"
license = "MIT"

[[mods]]
modId = "advanced_vanilla"
version = "${version}"
displayName = "Advanced Vanilla"
authors = "CAPTERSERS"
description = '''
Enhances vanilla items with new features and introduces a range of materials to enrich the classic experience.
'''
logoFile = "assets/advanced_vanilla/icon.png"
modUrl = "https://github.com/CAPTERSERS/Advanced-Vanilla"
displayURL = ""

[[dependencies.advanced_vanilla]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.advanced_vanilla]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.advanced_vanilla]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "advanced_vanilla.mixins.json"
