modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CAPTERSERS/CapterCraft/issues"
license = "MIT"

[[mods]]
modId = "captercraft"
version = "${version}"
displayName = "CapterCraft"
authors = "CAPTERSERS"
description = '''
Enhances vanilla items with new features and introduces a range of materials to enrich the classic experience.
'''
logoFile = "assets/captercraft/icon.png"
modUrl = "https://github.com/CAPTERSERS/CapterCraft"
displayURL = "https://captersers-org.gitbook.io/captersers-org"

[[dependencies.captercraft]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.captercraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.captercraft]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "captercraft.mixins.json"
